language: cpp
#need sudo for broken behavior of aclocal needed by sphinx base
sudo: true

branches:
  - master

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - swig
      - bison
      - autoconf
      - automake
      - libtool

env:
  - SPHINX_ROOT=${SPHINX_ROOT:-$(pwd)}

before_install:

install:
  - cd sphinxbase/
  - mkdir linux-default-build
  - BASE_INSTALL_LOCATION=$SPHINX_ROOT/sphinxbase/linux-default-build
  - sudo aclocal --verbose
  - sudo ./autogen.sh --prefix=$BASE_INSTALL_LOCATION
  - ./install.sh

before_script:

script:
  - ls #show the structure


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3eb8a998daf332f2703c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always