language: cpp
#need sudo for broken behavior of aclocal needed by sphinx base
sudo: true

branches:
  - master

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - swig
      - bison
      - autoconf
      - automake
      - libtool
      - portaudio-devel # this is disallowed

env:
  - SPHINX_ROOT=${SPHINX_ROOT:-$(pwd)}

before_install:
  - mkdir bin

install:
  - sudo -E apt-get install -yq --no-install-suggests --no-install-recommends --force-yes portaudio-devel
  - ./install.sh

before_script:

script:
  - ls #show the structure
  - python tests/single_word_unittest.py


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3eb8a998daf332f2703c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always