language: cpp
#run on latest container based infrastructure
sudo: false

branches:
  - master

compiler:
  - clang
  - gcc

env:

before_install:

install:
	- install.sh

before_script:

script:
	- ls #show the structure


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3eb8a998daf332f2703c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always