language: cpp
#need sudo for broken behavior of aclocal needed by sphinx base
sudo: true

branches:
  - master

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - swig
      - bison
      - autoconf
      - automake
      - libtool
      - portaudio19-dev

env:
  - SPHINX_ROOT=${SPHINX_ROOT:-$(pwd)}

before_install:
  - mkdir bin
  # - wget -P /tmp/portaudio http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
  # - tar -xzvf /tmp/portaudio/pa_stable_v19_20140130.tgz -C /tmp/portaudio/
  # - cd /tmp/portaudio/portaudio/ && ./configure && make clean
  # - make && sudo make install && ldconfig /usr/local/lib
  # - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  # - cd $SPHINX_ROOT

install:
  - ./install.sh

before_script:

script:
  - ls #show the structure
  - python tests/single_word_unittest.py

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3eb8a998daf332f2703c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always